### ISSUE TITLE
Update web map in Map Tools example

### ISSUE THREAD

**Issue by oevans** [Esri/map-tools-template#1]
The web map in the Map Tools example should be updated with a map that better highlights the app and web mapping best practices. The first item is a major issue; the others are minor.
- Major issue -- The Boston Marathon layer has random "null" polygons that should be removed and labels that conflict with the basemap (remove labels or change basemap).
- The layer also should be symbolized using one of the numeric attributes and it's name changed to something like "Boston Marathon Registrations."
- A second layer should be added to the map so that users can better see how the layer toggle tool works.
- The published layer should have field aliases. The table shows database-style field names with underscores and abbreviations.

![screen shot 2015-03-03 at 1 47 47 pm](https://cloud.githubusercontent.com/assets/3215530/6469593/e83b6780-c1ab-11e4-87e8-3d835ee3fc83.png)

**Comment by jgravois** [comment]
it'd be pretty trivial to swap in an entirely different webmap.  can you suggest an alternate?

i'd also recommend including a [View it live]() link in the README.

**Comment by kellyhutchins** [comment]
@oevans thanks we'll fix the map today.
