### ISSUE TITLE
Layer List Widget Open Automatically

### ISSUE THREAD

**Issue by jmmccallum1** [Esri/map-tools-template#14]
Hello,

Out of the box, I do not believe this template has the capability to have a widget open upon app load.  However, I have been playing around with the code and was wondering if someone could help me manipulate the code so that the layer list widget is open automatically upon app load?

Any help is appreciated!

**Comment by kellyhutchins** [comment]
@jmmccallum1  this geonet thread shows one approach for pre-expanding the layers: 

https://geonet.esri.com/thread/176905

**Comment by jmmccallum1** [comment]
@kellyhutchins Thanks for this!  I'm not too worried about individual layers being expanded within the layer list widget, I am more hoping that I can get the widget itself open/active upon initial load.  Basically, so the end user doesn't have to click on the layers icon to reveal the widget.

Something like this image below.

![image](https://cloud.githubusercontent.com/assets/19711809/15759294/cb4181b0-28d3-11e6-89f2-e55cc335e78c.png)

Thanks!

**Comment by kellyhutchins** [comment]
Ok that should be doable. Open main.js and at approximately line 818 you should see a line of code that reads this._updateTheme(). Right after that line add the following

```
        this._updateTheme();
        // automatically open the legend tool 
        this._displayContainer("layer_container", "layer_toggle");
```

Let me know if that gets you the behavior you want.

**Comment by jmmccallum1** [comment]
Awesome, this worked!  I apologize if my issue was a simple fix, I'm a bit of a novice in the coding world.  Trying to improve however!

Thanks again

**Comment by kellyhutchins** [comment]
No problem. Happy to help.
