### ISSUE TITLE
any documentation?

### ISSUE THREAD

**Issue by upcamogie** [Esri/map-tools-template#2]
I am looking for documentation that says what can and canont be done with the template. 
 It says to open the html and that is it. These templates would be more useful if they provided instructions. 
I see how you can have a layer list, table, etc. but that is it, nothing about how to actually alter the code if you want to set something up. and only one table? Please make a habit of providing instructions since most of these examples do not and its not only developers that would like to make map apps look nicer. thanks

**Comment by jgravois** [comment]
since our ArcGIS Online templates are based on our ArcGIS [API for JavaScript](https://developers.arcgis.com/javascript/jsapi/) and conventional HTML, there is actually an incredible amount of flexibility (and very few limitations) with regard to how they could conceivably be customized.

> nothing about how to actually alter the code if you want to set something up.

What exactly do you want to 'set up'?

**Comment by upcamogie** [comment]
I guess what I mean is that yes, the templates are useful if you are a developer and know the Java API. If you are a casual user who only wants to do a bit of customization, it is hard to work with no instructions on where you should alter some code for basic changes. I have had luck asking in these issues on how to add logos, etc. but really, basic explanation would be helpful. If I remember correctly, the text on how to use this app says look at the html file and go. When I looked at the html it did not look like that was where you added your webmap ID, etc, (Looked like you do that in a .js file), so to a user like me that is confusing.
There is not much in between the AGO templates , which are very limiting in looks but have instructions, and the templates here, which provide a lot of flexibility as you mention but no basic readme's. I appreciate all the samples but it is a disappointing to find that for web app templates w/ "no programming required" you can't do  much to make apps have 'your own' look without being a developer. It gives a false sense of what can really be accomplished without knowing java. I am getting by somewhat bu guessing where i need to change frame sizes, colors, etc. but it would just be nice to have a basic document on how things go together in these samples. Maybe gitbub isnt the right place since its for real developers and not code stealers like me but somewhere I would like a useful basic template that can be tweaked slightly to make it my own. And my ideal template would have all types of functionality in one app template. Some allow layer lists, some allow tables, very few allow everything (unless I just do not now how to expose this). And maybe one day I will be able to use a app template that will show my related records.

**Comment by kellyhutchins** [comment]
@upcamogie  you can customize quite a bit of the template using the configuration panel in ArcGIS Online. Once you do this the app url will contain an appid that you can specify in the downloaded version of the template and the customizations you made will be applied. 

For additional customizations try posting the questions to the JavaScript forum. I think the templates (and samples) are a great place to start digging around when you are trying to learn JavaScript. There are also some good online sites like Code School that provide intro courses in HTML, CSS and JavaScript and would be a good place to start if you want to learn how to make customizations.
