### ISSUE TITLE
Can not run the app

### ISSUE THREAD

**Issue by shivanit-cupertino** [Esri/map-tools-template#3]
gives the error: http://js.arcgis.com/3.13/init.js

TypeError: n.specificity is undefined

arguments[a]);c[b+"/"+g]=k;k.$locale=n.specificity;r()})})},v=function(a){var c=...

**Comment by kellyhutchins** [comment]
Can you provide more details about when this error occurs?

**Comment by shivanit-cupertino** [comment]
I downloaded the API, in web enabled directly and browse it using IIS manager.

**Comment by kellyhutchins** [comment]
It works for me in that scenario. Are you running the app using http:// or file://?

**Comment by shivanit-cupertino** [comment]
using the loacl host
http://localhost/map-tools-template-master/

**Comment by shivanit-cupertino** [comment]
SEC7118: XMLHttpRequest for http://www.arcgis.com/sharing/rest/portals/self?f=json required Cross Origin Resource Sharing (CORS). 
map-tools-template-master
SCRIPT5007: Unable to set property '$locale' of undefined or null reference 
3.13, line 58 character 28

**Comment by kellyhutchins** [comment]
Are you able to run other web apps? Maybe try downloading one of the samples from the JSAPI and seeing if it works. https://developers.arcgis.com/javascript/jssamples/#latest_samples

**Comment by shivanit-cupertino** [comment]
I can run Analysis - Create watersheds from the above link and it works. I have used map-tour and social-media-map tours api before and no complains.

**Comment by kellyhutchins** [comment]
I'm not sure what could be causing the issue. I can successfully download and run the template using my local web server. Are you using the default web map or did you replace the app to use one of your own?

**Comment by shivanit-cupertino** [comment]
i tried both

**Comment by shivanit-cupertino** [comment]
in fact I downloaded again and tried just now

**Comment by kellyhutchins** [comment]
I just asked a co-worker to test the download and it works for him too. I'm not sure what else to have you try.  Perhaps its a permissions issue of some sort? Also which browser are you using to test with?

**Comment by shivanit-cupertino** [comment]
i have tried chorme, firefox , explorer

**Comment by shivanit-cupertino** [comment]
thanks for your help. not sure whats going wrong

**Comment by shivanit-cupertino** [comment]
you did not change anything in the downloaded version and it ran fine? right?

**Comment by kellyhutchins** [comment]
Correct you shouldn't need to modify anything in the app. It should just run.

**Comment by shivanit-cupertino** [comment]
I downloaded this one more time and it worked
