### ISSUE TITLE
Can I add Interactive Filter template to map-tools template?

### ISSUE THREAD

**Issue by shivanit-cupertino** [Esri/map-tools-template#7]
This is not an issue though, was not sure where to post.

Can I add Interactive filter template http://www.arcgis.com/apps/InteractiveFilter/index.html  to this Map-tools app? If yes how tedious is the process ?

**Comment by kellyhutchins** [comment]
Yes you'd just need to copy over the necessary code from the Filter template. The Filter component isn't broken out into a separate class so it would be a bit of work to pull out the code. I pulled out the necessary code and added it to a copy of the Map Tools template. You can find the code here: 
https://dl.dropboxusercontent.com/u/24627279/MapTools.zip

**Comment by shivanit-cupertino** [comment]
Thanks so much Kelly. There are two subfolders in the zip file. Can you please confirm which one to use. Also when I try to put in my local server, it says A problem is preventing this folder from being encrypted. Do you want to copy this folder without encryption.

Thanks
Shivani

**Comment by kellyhutchins** [comment]
If there's a mac osx folder in the zip you can delete that its an artifact from zipping the file on a mac.
